myfind: myfind.c
#-Wall : Activates all Errors. The Compiler will inform the user about potential errors in the code.
#-Werror : It treats all warnings as errors. So the build will cancel, when warnings appear.
#-o: sets up the name for the executable
	gcc -Wall -Werror -o myfind myfind.c 
		
clean:
	rm -f myfind 

